CREATE TABLE USUARIO(
    ID CHAR(36) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(150) NOT NULL,
    TIPO_USUARIO ENUM('COMUM')NOT NULL
);

CREATE TABLE CATEGORIA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    TIPO ENUM('RECEITA','DESPESA','TRANSFERENCIA_META') NOT NULL,
    ID_USUARIO CHAR(36) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE TRANSACAO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    VALOR DECIMAL(19,2) NOT NULL,
    TIPO ENUM('RECEITA','DESPESA','TRANSFERENCIA_META') NOT NULL,
    DATA_TRANSACAO DATETIME NOT NULL,
    ID_USUARIO CHAR(36) NOT NULL,
    ID_CATEGORIA BIGINT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE META_FINANCEIRA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(150) NOT NULL,
    VALOR_OBJETIVO DECIMAL(19,2) NOT NULL,
    VALOR_ATUAL DECIMAL(19,2) NOT NULL,
    ATIVA BOOLEAN DEFAULT TRUE,
    DATA_LIMITE DATE NOT NULL,
    ID_USUARIO CHAR(36) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE DEPOSITO_META(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATA_DEPOSITO DATE NOT NULL,
    VALOR DECIMAL(19,2) NOT NULL,
    OBSERVACAO VARCHAR(100) NOT NULL,
    ID_TRANSACAO BIGINT NOT NULL,
    ID_META_FINANCEIRA BIGINT NOT NULL,
    FOREIGN KEY (ID_META_FINANCEIRA) REFERENCES META_FINANCEIRA(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_TRANSACAO) REFERENCES TRANSACAO(ID) ON DELETE CASCADE
);