ALTER TABLE DEPOSITO_META
    ADD COLUMN ID_USUARIO CHAR(36) NOT NULL,
    ADD CONSTRAINT UK_DEPOSITO_META_TRANSACAO UNIQUE (ID_TRANSACAO),
    ADD CONSTRAINT FK_DEPOSITO_META_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;

